[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mi-api-flask"
version = "0.1.0"
authors = [{name = "Tu Nombre"}]
dependencies = [
    "flask>=2.0"
]

[tool.hatch.envs.default]
dependencies = ["flask"]
